name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below clearly and completely.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps so we can reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: project_version
    attributes:
      label: Project version
      placeholder: e.g. v1.2.3
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 14.2, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: Paste full error messages here (use code blocks if possible).
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
          required: true
        - label: I have provided enough information to reproduce the issue.
          required: true
